AllItems = [
	'Vulnerary',
	'Door Key',
	'Bridge Key',
	'Chest Key',
	'Pure Water',
	'Power Ring',
	'Dragon Shield',
	'Secret Book',
	'Speed Ring',
	'Talisman',
	'Angelic Robe',
	'Goddess Icon',
	'Manual',
	'Boots',
	'Knight Crest',
	'Hero Crest',
	'Guiding Ring',
	'Elysian Whip',
	'Orion\'s Bolt',
	'Earth Orb',
	'Earth Orb2',
	'Shield of Seals',
	'Fire Emblem',
	'Dark Orb',
	'Aum',
	'Aum2',
	'Life Orb',
	'Iote Shield',
	'Aquarius Orb',
	'Pisces Orb',
	'Aries Orb',
	'Taurus Orb',
	'Gemini Orb',
	'Cancer Orb',
	'Leo Orb',
	'Virgo Orb',
	'Libra Orb',
	'Scorpio Orb',
	'Sagittarius Orb',
	'Capricorn Orb',
	'Silver Card',
	'Member Card',
	'Light Orb',
	'Star Orb'
]
ImportantItems = [
	'Earth Orb',
	'Earth Orb2',
	'Shield of Seals',
	'Fire Emblem',
	'Dark Orb',
	'Aum',
	'Aum2',
	'Life Orb',
	'Iote Shield',
	'Aquarius Orb',
	'Pisces Orb',
	'Aries Orb',
	'Taurus Orb',
	'Gemini Orb',
	'Cancer Orb',
	'Leo Orb',
	'Virgo Orb',
	'Libra Orb',
	'Scorpio Orb',
	'Sagittarius Orb',
	'Capricorn Orb',
	'Silver Card',
	'Member Card',
	'Light Orb',
	'Star Orb'
]

WeaponItems = [
	'Iron Sword',
	'Steel Sword',
	'Silver Sword',
	'Rapier',
	'Killing Edge',
	'Devil Sword',
	'Master Sword',
	'Lady Sword',
	'Levin Sword',
	'Mercurius',
	'Falchion',
	'Armorslayer',
	'Wyrmslayer',
	'Sword Killer',
	'Iron Lance',
	'Steel Lance',
	'Silver Lance',
	'Horseslayer',
	'Javelin',
	'Killer Lance',
	'Slim Lance',
	'Gradivus',
	'Iron Bow',
	'Steel Bow',
	'Silver Bow',
	'Killer Bow',
	'Parthia',
	'Iron Axe',
	'Steel Axe',
	'Hand Axe',
	'Silver Axe',
	'Devil Axe',
	'Thunderbolt',
	'Arrowspate',
	'Stonehoist',
	'Hoistflamme',
	'Pachyderm',
	'Fire Breath',
	'Fire Breath',
	'Ice Breath',
	'Dark Breath',
	'Mist Breath',
	'Fire',
	'Thunder',
	'Blizzard',
	'Shaver',
	'Elfire',
	'Thoron',
	'Bolganone',
	'Excalibur',
	'Aura',
	'Starlight',
	'Imhullu',
	'Dulam',
	'Nosferatu',
	'Meteor',
	'Swarm'
]
ShopItems = [
	'Iron Sword',
	'Steel Sword',
	'Silver Sword',
	'Killing Edge',
	'Devil Sword',
	'Master Sword',
	'Levin Sword',
	'Armorslayer',
	'Wyrmslayer',
	'Sword Killer',
	'Iron Lance',
	'Steel Lance',
	'Silver Lance',
	'Horseslayer',
	'Javelin',
	'Killer Lance',
	'Slim Lance',
	'Iron Bow',
	'Steel Bow',
	'Silver Bow',
	'Killer Bow',
	'Iron Axe',
	'Steel Axe',
	'Hand Axe',
	'Silver Axe',
	'Devil Axe',
	'Fire',
	'Thunder',
	'Blizzard',
	'Shaver',
	'Elfire',
	'Thoron',
	'Bolganone',
	'Nosferatu',
	'Rapier',
	'Heal',
	'Recover',
	'Physic',
	'Mend',
	'Warp',
	'Barrier',
	'Fortify',
	'Rescue',
	'Thief',
	'Anew',
	'Firestone',
	'Vulnerary',
	'Door Key',
	'Bridge Key',
	'Chest Key',
	'Power Ring',
	'Dragon Shield',
	'Secret Book',
	'Speed Ring',
	'Talisman',
	'Angelic Robe',
	'Goddess Icon',
	'Manual',
	'Boots',
	'Pure Water',
	'Knight Crest',
	'Hero Crest',
	'Guiding Ring',
	'Elysian Whip',
	'Orion\'s Bolt'
]